ElasticNet:
  alpha: 0.2
  l1_ratio: 0.1
  max_iter: 1000
  random_state: 42

MultiOutput:
  enabled: true
  targets:
    - Milk_500ml_Demand
    - Milk_1L_Demand
    - Butter_Demand
    - Cheese_Demand
    - Yogurt_Demand

DataSplit:
  test_size: 0.2
  random_state: 42